# Generated by Django 5.2.1 on 2025-05-23 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tramites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='curriculos/')),
                ('metadata', models.JSONField()),
                ('puntuacion', models.FloatField(default=0.0)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.ciudadano')),
            ],
        ),
    ]
